### ISSUE TITLE
Node.js support and npm package

### ISSUE THREAD

**Issue by ericf** [andyearnshaw/Intl.js#20]
We are interested in using `Intl.js` in browsers which don't have the built-in `Intl` APIs _and_ in Node.js.

It's still up in the air on whether Node.js binaries will ship with v8-i18n linked. There's a long discussion with [inaccurate] worries about the size of bundling the required parts of ICU. If this stays a compile-time flag for Node.js, it effectively means that the `Intl` APIs will not exist in Node.js :(

See: https://github.com/joyent/node/issues/4689#issuecomment-26457622 and https://github.com/joyent/node/issues/6371

I would like to hedge this by being able to use this polyfill as an npm package and run it in Node.js. Would you be on board with adding the [umd wrap](https://github.com/umdjs/umd) (or similar) around this code instead of assuming `window` exists in the runtime? Also would you be on board with publishing this as an npm package?

I am willing to open a PR for this, but I want to make sure that you're on board with this idea before I do so. Thanks!
### Todos:
- [x] Don't assume this is running in a browser with `window`
- [x] Add umd wrapper
- [x] Add package.json and publish to npm

**Comment by saran110313** [comment]
features.js compatibility browser support in whiteboard on node.js
