### ISSUE TITLE
[task] release 1.3.0

### ISSUE THREAD

**Issue by caridy** [andyearnshaw/Intl.js#203]
Features and Fixes:

 * [ ] trim pkg size (issue #199)
 * [x] single configuration options (issue #195 )
 * [x] restoring regexp options (issue #196)
 * [x] improve bestFit to match browsers
 * [ ] restore IE8 support (issue #189)
 * [ ] clear up FT polyfill service update
